// scripts/generate.js
// Run: node scripts/generate.js
// Requires: ANTHROPIC_API_KEY, NEWS_API_KEY, BEEHIIV_API_KEY, BEEHIIV_PUB_ID env vars

import Anthropic from "@anthropic-ai/sdk";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const SPORTS = [
  { name: "NFL", query: "NFL football news" },
  { name: "NBA", query: "NBA basketball news" },
  { name: "MLB", query: "MLB baseball news" },
  { name: "College Sports", query: "college football basketball NCAA news" },
  { name: "Soccer/EPL", query: "Premier League soccer football news" },
  { name: "F1", query: "Formula 1 F1 racing news" },
  { name: "Tennis", query: "tennis ATP WTA news" },
  { name: "NHL", query: "NHL hockey news" },
  { name: "Golf", query: "PGA golf news" },
];

async function fetchNewsForSport(sport) {
  const apiKey = process.env.NEWS_API_KEY;
  if (!apiKey) throw new Error("NEWS_API_KEY not set");

  const url = `https://newsapi.org/v2/everything?q=${encodeURIComponent(sport.query)}&sortBy=publishedAt&pageSize=5&language=en&apiKey=${apiKey}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`NewsAPI error for ${sport.name}: ${res.status}`);
  const data = await res.json();

  return data.articles
    .slice(0, 5)
    .map((a) => `- ${a.title}: ${a.description || ""}`)
    .join("\n");
}

async function generateSection(client, sport, rawNews) {
  const prompt = `You're writing the ${sport.name} section of a casual, conversational weekly sports digest called "The Weekly Rundown." 

Here are this week's raw headlines and news snippets for ${sport.name}:
${rawNews}

Write a digest section with 2-3 stories. For each story:
- A punchy headline (not just the article title — rewrite it with personality)
- 2-3 sentences of casual, conversational commentary. Not dry recapping — more like a knowledgeable friend catching you up. Light humor is welcome but don't force it.
- A short tag (1-3 words) categorizing the story type, like "Trade Rumors", "Standings", "Injury Update", "Big Win", "Drama", etc.

Return ONLY valid JSON in this exact format, no markdown:
{
  "sport": "${sport.name}",
  "stories": [
    {
      "headline": "...",
      "body": "...",
      "tag": "..."
    }
  ]
}`;

  const message = await client.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 800,
    messages: [{ role: "user", content: prompt }],
  });

  const text = message.content[0].text.trim();
  return JSON.parse(text);
}

async function generateIntro(client, sections) {
  const headlines = sections
    .flatMap((s) => s.stories.slice(0, 1).map((st) => `${s.sport}: ${st.headline}`))
    .join(", ");

  const message = await client.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 200,
    messages: [
      {
        role: "user",
        content: `Write a 2-sentence casual intro for a weekly sports digest called "The Weekly Rundown." This week's biggest stories include: ${headlines}. Keep it breezy and fun, like a friend kicking off a recap.`,
      },
    ],
  });

  return message.content[0].text.trim();
}

function digestToHtml(intro, sections) {
  const sportIcons = {
    NFL: "🏈", NBA: "🏀", MLB: "⚾", "College Sports": "🎓",
    "Soccer/EPL": "⚽", F1: "🏎️", Tennis: "🎾", NHL: "🏒", Golf: "⛳",
  };

  const sectionsHtml = sections.map((s) => `
    <h2 style="font-family:sans-serif;margin-top:32px;">${sportIcons[s.sport] || ""} ${s.sport}</h2>
    ${s.stories.map((st) => `
      <div style="margin-bottom:20px;padding:16px;background:#f9f9f9;border-radius:8px;">
        <strong style="font-family:sans-serif;font-size:15px;">${st.headline}</strong>
        <span style="display:inline-block;margin-left:8px;font-size:11px;background:#e8ff47;color:#000;padding:2px 8px;border-radius:4px;">${st.tag}</span>
        <p style="font-family:sans-serif;font-size:14px;color:#444;margin-top:8px;">${st.body}</p>
      </div>
    `).join("")}
  `).join("");

  return `
    <div style="max-width:600px;margin:0 auto;padding:24px;">
      <h1 style="font-family:sans-serif;">⚡ The Weekly Rundown</h1>
      <p style="font-family:sans-serif;color:#555;">${intro}</p>
      ${sectionsHtml}
      <p style="font-family:sans-serif;font-size:12px;color:#999;margin-top:32px;">Generated by AI · Updated every Monday</p>
    </div>
  `;
}

async function postToBeehiiv(digest) {
  const apiKey = process.env.BEEHIIV_API_KEY;
  const pubId = process.env.BEEHIIV_PUB_ID;
  if (!apiKey || !pubId) throw new Error("BEEHIIV_API_KEY or BEEHIIV_PUB_ID not set");

  const date = new Date(digest.generatedAt).toLocaleDateString("en-US", {
    month: "long", day: "numeric", year: "numeric",
  });

  const html = digestToHtml(digest.intro, digest.sections);

  const res = await fetch(`https://api.beehiiv.com/v2/publications/${pubId}/posts`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      title: `The Weekly Rundown — ${date}`,
      subtitle: digest.intro,
      content_html: html,
      status: "draft",
      send_at: new Date().toISOString(),
    }),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Beehiiv error: ${res.status} ${err}`);
  }

  return await res.json();
}

async function main() {
  console.log("🏆 Generating sports digest...\n");

  const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
  const sections = [];

  for (const sport of SPORTS) {
    try {
      process.stdout.write(`Fetching ${sport.name} news...`);
      const rawNews = await fetchNewsForSport(sport);
      process.stdout.write(" ✓ Writing section...");
      const section = await generateSection(client, sport, rawNews);
      sections.push(section);
      console.log(` ✓ Done`);
    } catch (err) {
      console.log(` ✗ Skipped (${err.message})`);
    }
  }

  console.log("\nWriting intro...");
  const intro = await generateIntro(client, sections);

  const digest = {
    generatedAt: new Date().toISOString(),
    intro,
    sections,
  };

  const outputPath = path.join(__dirname, "../public/digest.json");
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, JSON.stringify(digest, null, 2));

  console.log(`\n✅ Digest written to public/digest.json`);
  console.log(`   ${sections.length} sports covered`);

  if (process.env.BEEHIIV_API_KEY && process.env.BEEHIIV_PUB_ID) {
    try {
      process.stdout.write("\nPosting to Beehiiv...");
      await postToBeehiiv(digest);
      console.log(" ✅ Newsletter sent!");
    } catch (err) {
      console.log(` ✗ Beehiiv failed (${err.message})`);
    }
  } else {
    console.log("\nℹ️  Skipping Beehiiv (keys not set)");
  }
}

main().catch((err) => {
  console.error("❌ Error:", err.message);
  process.exit(1);
});
