import { useState, useEffect } from "react";

const SPORTS_ICONS = {
  NFL: "🏈",
  NBA: "🏀",
  MLB: "⚾",
  "College Sports": "🎓",
  "Soccer/EPL": "⚽",
  F1: "🏎️",
  Tennis: "🎾",
  NHL: "🏒",
  Golf: "⛳",
};

function DigestSection({ section }) {
  const [open, setOpen] = useState(true);
  return (
    <div className="section">
      <button className="section-header" onClick={() => setOpen(!open)}>
        <span className="section-title">
          <span className="section-icon">{SPORTS_ICONS[section.sport] || "📰"}</span>
          {section.sport}
        </span>
        <span className={`chevron ${open ? "open" : ""}`}>›</span>
      </button>
      {open && (
        <div className="section-body">
          {section.stories.map((story, i) => (
            <div key={i} className="story">
              <div className="story-headline">{story.headline}</div>
              <div className="story-body">{story.body}</div>
              {story.tag && <span className="story-tag">{story.tag}</span>}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function LoadingSkeleton() {
  return (
    <div className="loading">
      {[1, 2, 3].map((i) => (
        <div key={i} className="skeleton-section">
          <div className="skeleton-header shimmer" />
          <div className="skeleton-body">
            <div className="skeleton-line shimmer" style={{ width: "90%" }} />
            <div className="skeleton-line shimmer" style={{ width: "75%" }} />
            <div className="skeleton-line shimmer" style={{ width: "82%" }} />
          </div>
        </div>
      ))}
    </div>
  );
}

export default function App() {
  const [digest, setDigest] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [activeFilter, setActiveFilter] = useState("All");

  useEffect(() => {
    fetch("/digest.json")
      .then((r) => {
        if (!r.ok) throw new Error("No digest found");
        return r.json();
      })
      .then((data) => {
        setDigest(data);
        setLoading(false);
      })
      .catch(() => {
        setError("Digest hasn't been generated yet. Run the generator script to get started.");
        setLoading(false);
      });
  }, []);

  const sports = digest ? ["All", ...digest.sections.map((s) => s.sport)] : [];
  const filtered =
    digest && activeFilter === "All"
      ? digest.sections
      : digest?.sections.filter((s) => s.sport === activeFilter);

  return (
    <div className="app">
      <header className="header">
        <div className="header-inner">
          <div className="logo">
            <span className="logo-mark">⚡</span>
            <div>
              <div className="logo-title">The Weekly Rundown</div>
              <div className="logo-sub">Sports digest, every Monday</div>
            </div>
          </div>
          {digest && (
            <div className="week-badge">
              Week of {new Date(digest.generatedAt).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}
            </div>
          )}
        </div>
      </header>

      {digest && (
        <div className="filter-bar">
          <div className="filter-inner">
            {sports.map((sport) => (
              <button
                key={sport}
                className={`filter-btn ${activeFilter === sport ? "active" : ""}`}
                onClick={() => setActiveFilter(sport)}
              >
                {sport !== "All" && <span>{SPORTS_ICONS[sport]}</span>}
                {sport}
              </button>
            ))}
          </div>
        </div>
      )}

      <main className="main">
        {loading && <LoadingSkeleton />}
        {error && (
          <div className="error-card">
            <div className="error-icon">📭</div>
            <div className="error-title">No digest yet</div>
            <div className="error-body">{error}</div>
            <code className="error-code">node scripts/generate.js</code>
          </div>
        )}
        {digest && !loading && (
          <>
            {digest.intro && <p className="intro-text">{digest.intro}</p>}
            <div className="sections">
              {filtered.map((section, i) => (
                <DigestSection key={i} section={section} />
              ))}
            </div>
            <footer className="footer">
              Generated by AI · <span>Updated weekly</span>
            </footer>
          </>
        )}
      </main>
    </div>
  );
}
